name: Build firmware as CI

on:
    push:
        paths:
        - quantum/**/*
        - tmk_core/**/*
        - drivers/**/*
        - tests/**
        - util/**/*
        - platforms/**/*
        - '*.mk'
        - Makefile
        - keyboards/sofle/**/*
        - keyboards/dm9records/plaid/**/*
    pull_request:
        paths:
        - quantum/**/*
        - tmk_core/**/*
        - drivers/**/*
        - tests/**
        - util/**/*
        - platforms/**/*
        - '*.mk'
        - Makefile
        - keyboards/sofle/**/*
        - keyboards/dm9records/plaid/**/*

jobs:
  build_firmware:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    # Only run in my fork
    if: github.repository == 'dantho281/qmk_firmware'

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        submodules: true

    - name: Build firmware
      run: qmk compile -kb sofle -km dantho281 && qmk compile -kb dm9records/plaid -km danthe281

    - uses: actions/upload-artifact@v2
      with:
        name: firmware-sofle-${{github.sha}}
        path: /__w/qmk_firmware/qmk_firmware/sofle_rev1_dantho281.hex

    - uses: actions/upload-artifact@v2
      with:
        name: firmware-plaid-${{github.sha}}
        path: /__w/qmk_firmware/qmk_firmware/dm9records_plaid_dantho281.hex
